FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ConsumidorRabbitMQ.csproj", "./"]
RUN dotnet restore "ConsumidorRabbitMQ.csproj"
COPY . .
RUN dotnet publish "ConsumidorRabbitMQ.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "ConsumidorRabbitMQ.dll"]